### ISSUE TITLE
eslint-plugin-mdx 에러

### ISSUE THREAD

**Issue by HerrineKim** [HerrineKim/homepage#11]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

markdown linter가 처음에는 잘 작동했는데 eslint 최신 버전 사용 시 발생했었던 에러와 같은 에러를 밷고 있습니다.

```
Consider running eslint --debug C:\00_My_Programming\my_github\homepage\src\app\wiki\page.tsx from a terminal to obtain a trace about the configuration files used.
[Error - 9:42:12 PM] 
Failed to load plugin 'mdx' declared in '.eslintrc': Cannot find module 'eslint-plugin-mdx'
Require stack:
- C:\00_My_Programming\my_github\homepage\__placeholder__.js
Referenced from: C:\00_My_Programming\my_github\homepage\.eslintrc
Happened while validating C:\00_My_Programming\my_github\homepage\next.config.js
This can happen for a couple of reasons:
1. The plugin name is spelled incorrectly in an ESLint configuration file (e.g. .eslintrc).
2. If ESLint is installed globally, then make sure 'eslint-plugin-mdx' is installed globally as well.
3. If ESLint is installed locally, then 'eslint-plugin-mdx' isn't installed correctly.
```

### Describe the solution you'd like

eslint와 같은 경우 vscode settings.json 파일에 workingDirectories를 명시해주는 걸로 해결이 됐었는데요, 이번 에러는 따로 지정할 수 있는 옵션이 있는지, 같은 걸로 해결이 되는지도 모르는 상태입니다.

```json
  "eslint.workingDirectories": [
    "./src"
  ],
``` 

### What is the motivation / use case for changing the behavior?

중요도가 낮은 에러라서 프로젝트 진행하면서 해결하려구 합니다

**Comment by raymondanythings** [comment]
너무생소하고 신기한 기술이라  내일 리뷰시간에 마크다운 린터 설명 조금만 해주시면 감사하겠습니다 ㅎㅎ

**Comment by HerrineKim** [comment]
아마 mdx가 아니라 mardown으로 바꿔야 하는 것 같네요..ㅎ 이번 주 내로 적용 도전!
