### ISSUE TITLE
Promise.all + TypeScript + fetch ?

### ISSUE THREAD

**Issue by HerrineKim** [HerrineKim/homepage#20]
### Is there an existing issue that is already proposing this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

```javascript
  const seoulPromise = fetch(`${baseURL}/Asia/Seoul`)
  const cityPromise = fetch(`${baseURL}${cityName}`)

  useEffect(() => {
    Promise.all([seoulPromise, cityPromise])
      .then((responses) => responses.map((el) => el.json()))
      .then((data) => Promise.all(data))
      .then((data) => {
        const thisSeoulTime = new Date(data[0].datetime.split('.')[0])
        const thisCityTime = new Date(data[1].datetime.split('.')[0])

        let tempTimeOffset = thisSeoulTime.getTime() - thisCityTime.getTime()
        if (tempTimeOffset < 0) {
          setIsAhead(true)
          tempTimeOffset = tempTimeOffset * -1
        } else {
          setIsBehind(true)
        }
        const tempTimeOffsetHour = Math.floor(tempTimeOffset / 3600000)
        setOffset(tempTimeOffsetHour)

        setCityTime(
          thisCityTime.getHours() * 3600 +
            thisCityTime.getMinutes() * 60 +
            thisCityTime.getSeconds(),
        )
        setCityTimeAbb(data[1].abbreviation.replace('+08', 'SNST'))
      })
      .catch((error) => {
        throw new Error(error)
      })
  }, [cityName])
  
```
세계 시계에서 사용한 promise.all 함수에서 자꾸 json 처리가 두 번 됐다고 warning이 나오기도 하고, 더 명시적으로 수정하는 과정에서 타입에러도 발생해서 파헤쳐 보는 중입니다

### Describe the solution you'd like

.

### What is the motivation/use case for changing the behavior?

작동에 이상은 없지만 에러나 경고 나오지 않도록 고쳐보려고 합니다!

**Comment by raymondanythings** [comment]
오... 확실하진 않지만 

```javascript
Promise.all([seoulPromise, cityPromise])
         //  map()이 반환하는 값이 [Promise,Promise] 아닐까싶어요
      .then((responses) => responses.map((el) => el.json()))
      .then((data) => Promise.all(data))
      .then((data) => {
        const thisSeoulTime = new Date(data[0].datetime.split('.')[0])
        const thisCityTime = new Date(data[1].datetime.split('.')[0])
// ....
```


만약 그렇다면 
```javascript
Promise.all([seoulPromise, cityPromise])
         //  map()이 반환하는 값이 [Promise,Promise] 아닐까싶어요
      .then((responses) => Promise.all(responses.map((el) => el.json())))
      .then((data) => Promise.all(data))
      .then((data) => {
        const thisSeoulTime = new Date(data[0].datetime.split('.')[0])
        const thisCityTime = new Date(data[1].datetime.split('.')[0])
// ....
```

이렇게 바꾸는게 맞는 표현이 아닐까 싶습니다!

**Comment by HerrineKim** [comment]
> 오... 확실하진 않지만
> 
> ```js
> Promise.all([seoulPromise, cityPromise])
>          //  map()이 반환하는 값이 [Promise,Promise] 아닐까싶어요
>       .then((responses) => responses.map((el) => el.json()))
>       .then((data) => Promise.all(data))
>       .then((data) => {
>         const thisSeoulTime = new Date(data[0].datetime.split('.')[0])
>         const thisCityTime = new Date(data[1].datetime.split('.')[0])
> // ....
> ```
> 
> 만약 그렇다면
> 
> ```js
> Promise.all([seoulPromise, cityPromise])
>          //  map()이 반환하는 값이 [Promise,Promise] 아닐까싶어요
>       .then((responses) => Promise.all(responses.map((el) => el.json())))
>       .then((data) => {
>         const thisSeoulTime = new Date(data[0].datetime.split('.')[0])
>         const thisCityTime = new Date(data[1].datetime.split('.')[0])
> // ....
> ```
> 
> 이렇게 바꾸는게 맞는 표현이 아닐까 싶습니다!

바꿔도 똑같네요 🤔 알 수 없다...^^

![image](https://user-images.githubusercontent.com/96880085/224855775-261751b4-bf3c-4646-8e5e-9e7cabd575e7.png)

**Comment by raymondanythings** [comment]
> > 오... 확실하진 않지만
> > ```js
> > Promise.all([seoulPromise, cityPromise])
> >          //  map()이 반환하는 값이 [Promise,Promise] 아닐까싶어요
> >       .then((responses) => responses.map((el) => el.json()))
> >       .then((data) => Promise.all(data))
> >       .then((data) => {
> >         const thisSeoulTime = new Date(data[0].datetime.split('.')[0])
> >         const thisCityTime = new Date(data[1].datetime.split('.')[0])
> > // ....
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 만약 그렇다면
> > ```js
> > Promise.all([seoulPromise, cityPromise])
> >          //  map()이 반환하는 값이 [Promise,Promise] 아닐까싶어요
> >       .then((responses) => Promise.all(responses.map((el) => el.json())))
> >       .then((data) => {
> >         const thisSeoulTime = new Date(data[0].datetime.split('.')[0])
> >         const thisCityTime = new Date(data[1].datetime.split('.')[0])
> > // ....
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 이렇게 바꾸는게 맞는 표현이 아닐까 싶습니다!
> 
> 바꿔도 똑같네요 🤔 알 수 없다...^^
> 
> ![image](https://user-images.githubusercontent.com/96880085/224855775-261751b4-bf3c-4646-8e5e-9e7cabd575e7.png)

로컬에서 빌드 후 테스트 해보니까 정상작동하는 것 같아요
리액트 18버전에 lifecycle hook이 개발모드에서 여러번 호출되는 것 때문이지 않을까 예상해봅니다..ㅎㅎ

**Comment by HerrineKim** [comment]
> > > 오... 확실하진 않지만
> > > ```js
> > > Promise.all([seoulPromise, cityPromise])
> > >          //  map()이 반환하는 값이 [Promise,Promise] 아닐까싶어요
> > >       .then((responses) => responses.map((el) => el.json()))
> > >       .then((data) => Promise.all(data))
> > >       .then((data) => {
> > >         const thisSeoulTime = new Date(data[0].datetime.split('.')[0])
> > >         const thisCityTime = new Date(data[1].datetime.split('.')[0])
> > > // ....
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 만약 그렇다면
> > > ```js
> > > Promise.all([seoulPromise, cityPromise])
> > >          //  map()이 반환하는 값이 [Promise,Promise] 아닐까싶어요
> > >       .then((responses) => Promise.all(responses.map((el) => el.json())))
> > >       .then((data) => {
> > >         const thisSeoulTime = new Date(data[0].datetime.split('.')[0])
> > >         const thisCityTime = new Date(data[1].datetime.split('.')[0])
> > > // ....
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 이렇게 바꾸는게 맞는 표현이 아닐까 싶습니다!
> > 
> > 
> > 바꿔도 똑같네요 🤔 알 수 없다...^^
> > ![image](https://user-images.githubusercontent.com/96880085/224855775-261751b4-bf3c-4646-8e5e-9e7cabd575e7.png)
> 
> 로컬에서 빌드 후 테스트 해보니까 정상작동하는 것 같아요 리액트 18버전에 lifecycle hook이 개발모드에서 여러번 호출되는 것 때문이지 않을까 예상해봅니다..ㅎㅎ

오옷 정상 작동은 해도, 콘솔에 에러 메시지 뜨지 않았나요? 아니면 너무 좋네요!!
