### ISSUE TITLE
.md 파일이 담긴 폴더를 읽어오지 못하는 문제

### ISSUE THREAD

**Issue by HerrineKim** [HerrineKim/homepage#8]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

마크다운 파일들을 불러오려면 파일들이 담긴 폴더에 접근해야 합니다. 하지만 VSCode 상에서 옳게 접근해도 없는 폴더라고 나오는 문제가 있습니다.

### Describe the solution you'd like

[영상](https://www.youtube.com/watch?v=Hiabp1GY8fA)을 참고해 진행하고 있습니다. 아마 fs 모듈에서 폴더를 탐색하는 방식이 일반적인 방법과 다른 건가 추측하고 있습니다.

### What is the motivation / use case for changing the behavior?

.

**Comment by raymondanythings** [comment]
비슷한 환경으로 테스트 해본 결과 잘 작동하는 것으로 보이네요 
내일 현상 확인해봐야 알 것 같습니다 ㅠㅠ

**Comment by HerrineKim** [comment]
> 비슷한 환경으로 테스트 해본 결과 잘 작동하는 것으로 보이네요 내일 현상 확인해봐야 알 것 같습니다 ㅠㅠ

  const folder = 'src\\app\\wiki\\posts'

좀 전에 이렇게 고쳤더니 됐습니다 🤣  이전 프로젝트들에서는 그냥 슬래쉬 / 하나로 됐었는데 왜 이번만 그런지는 좀 더 연구가 필요하네요 ㅎㅎ

**Comment by HerrineKim** [comment]
유닉스 계열 운영체제와 윈도우즈 운영체제느 서로 다른 방식으로 경로를 표시합니다. 따라서 단순 문자열로 경로를 나타내는 코드를 짜는 건 바람직하지 못합니다!!

이 때 사용되는 것이 node.js에 내장된 path 모듈입니다. 구분자를 뭘 쓰든 특정 디렉토리를 반환해 줍니다. 이 외에도 확장자 얻기, 경로 만들기 등 다양한 기능을 제공합니다!

[관련 링크](https://www.daleseo.com/js-node-path/)

(thanks to 용현님 @raymondanythings)
